# Generated by Django 3.2.15 on 2022-08-17 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="Amount in the smallest, integer currency parts (eg. cents)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
